name: Android Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Build Release AAB      // 1
        run: ./gradlew bundleRelease

      - name: Sign AAB               // 2
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: "MIIJVwIBAzCCCRAGCSqGSIb3DQEHAaCCCQEEggj9MIII+TCCBWUGCSqGSIb3DQEHAaCCBVYEggVSMIIFTjCCBUoGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBQYV6CGp1nD+8jYD2hqt6FK3su5VAIDAMNQBIIEyDNQ3j+FHZxqiFSTG0VXfQFv5uPtrKye1GKfMNUYQ4dlMR0qaecy3w9ow4/gxDOESo8C6tyTrib/B6XHDTzJrJRWrWswHX/ql/yzMQSji77vclkFUdNYQ5uapdDQDk3u/ExXv3pC/RIvWtYnEGEvNTqTcYblmK5TUWfXMJ7XeLvlJLICwP/2bX/NNt/1VtIZcU70eleyZ5lc9GzzpIyIvffo7DllIPwfxNw2YkAchSurIeQq06BXOFVWmKalFPjyJjKOBRGGVFrSxY2aEgkXQBTj8Ado+75puOmOy2juL5QhPDmG4MsAe3t+v+VDqI+WkOl5DNmJWdqxcLrzSbGE9NTLvMeT22uhQkuwP9f4P428h//NXDsyFHppjcXzOC3JNDdOLHdlXe96Zajx8JNeuMVIlwcpPltziIvqVDOuszk0HxyVfWYWe7kvU05h1BozmzDgQSMjHnf7zaw2+2dowXAtGOxLxpczx6w8c5j/yabTjh9cLpGMibo/tVVqEVK9qjQ0znm8c72PzgRhtH7nQg1ifQINq13SSDgh1iEiYdomwOnzFLItECw1RxDs3Q6LGZrHe01NcKcFO9Z/pgdlZTr2Uq73m76vAwHUqEVDO2DKOJXsL5Ge9eK2+CeOp9kGhTodJREVVNvjQg9zFfrlf6WtfA2cOHTFLiQCNQkDaFfU6iEk+0D83PN7q4SCXZD9c4PXXYEfwCPZ2kkqS+MSVHOdsGyxxgQggsy58+4uKm/enaVdemVwge1oo1u379VzKZYq+I86ZUjcE+pZJOHzCvHEJnzSZXTmJbqnajza54C6DuF13VXazX+iCnrA2tVtCbm9LibhN9CKPfwgCDheg6zegl5SZLdyo4zdO0im75Oy7InwEPOEnhWa0lQvieoFWy0zhW5NeZPuCyjMxQtTepnCDDfGto2QtIDZKmQr/choSAH4tfievE6n9+SiFo5s4pbb4GciHgJD6seD4c8BZcL0tSyhUKuMgvYm47XJvl82o6Uyw7Oz7zg2VQeNO2q/bb3BVJfhj7kLvbzESXGakNFAiqiKu7iCcxGXm3IdsFT/YjISzYNsamGXBtgN9NSVgQvhvoiw0o1rkdYxRcZlj4NHFIguC0oMpTbKP1f85xmy2REfPAI2uf5asiQg7PNdhd3rSAILlRXqRs35/OILS0C0bZeM2pibjNYdUuQ/tGVJeXmIf2PxKq3JLv8w3p+2CgVrc+rMrJ0zLTIE5dB4onYBNrikCUXdYw/jVQTbZ33Y/WizWUYAMiKmlXcRlnX6ZC1i8q8A291j5aVCNKNoQpqpVDjX5xwYk6siX2EHU1hhecsxl4BUmwjeJ4Ibod/y0LO4skkpnFczAYQmpRhYS7skZSJAxndt3BWpOX/gEw9zkaWFdQ8TznG/+OF2osmjIzH8Q+LpCeG2JvEFNekH4W2Z35IP/e7sh/QJHbSrRaFHABmB0MvJUIMvqBn+LB/YSpF2RAFO8tu6CcNGcx36l9nycCGz6PQ/82aMYAwA7KqBJRYOZKVAiBSanSLJUHnVsDnIYQw8PXW6loxVvWcbk89HKaM7G0bPlCG+dP1yWAsX0jFR8F3TdSTt+rdHCawPMC2GBVnir+zTtX7VGD5RSX7eFj0PsvrGrzE8MBcGCSqGSIb3DQEJFDEKHggAdABlAHMAdDAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNjMzMzQwNjU5NTc0MIIDjAYJKoZIhvcNAQcGoIIDfTCCA3kCAQAwggNyBgkqhkiG9w0BBwEwKQYKKoZIhvcNAQwBBjAbBBTy1zxq/u3T+zTkawD/u9C47dbVJgIDAMNQgIIDOAihJLCcvw98pDzxWW1P9Ff1yJsYiP0xll0I2LFbpEqIaVJvdDY7jiudpXS2NJuhJgklVh5STLbGpMxjwZ2AeXjjQ6hutGFETx7bQpPwobyBCi/4t/IDT+t9PHDyJeqzgoNI7tDv65mr6g6Lb36HZRBGhiBq1sgO+GU+bFzvZrhd7gUgiEebIJRerZdcK/QbG6QJLH1C3i8ecFqBBfhCWxaIvm6BrsZdmXXuKE+3a+OMEgSlwcU0KNXx2pF2vgcdpxfdJFfnB59CRdrTpK/ZRhsCEG4TpVku2GtIf7AiXpglxZX8cLXumE7WtKXwvoC6DyCBhD8m6jMnsmrdAd9dAcGBRj2mST02OCj9TGdiHjJfDAxX5IIw2cdItEqCv9Qn1K7yPBHmrlZANF/FcyOOexD5KMXqRUDt4CQxpNRmrSsBBVYzsBbGc3lkfFUJPHfuA8MG+J4RMTd750IdHSzM7n7SnQ2aJGGJVCiDRKZMEJ3CAUW37BfZ2F0IS74+Mv0gbgJ9CB2bRTHHZGsh6WhzT5fBuBgmy3ygRHc5NizpCZJx/4sYWny6dTAetpUb35H8Hbx6tnt19GJx/XNba08eBIDSkJq+MvN4pJEcvyndZzpxY91Ze5/18FWQl42xCkl/cEFF9sh4KcVEFE3TGwHk3gOr8LXKdmhzf7V3eiGcFyJTQdAIIqCUXe2AsZ0yn2mAHZKxR8KjESQ63dy3MJyPNXbNsWlayaeXPM1gd82A+66fpqKLBNpBn0oUEBxK/QsvceVu28Q8WVg3cSFriyJGdD/1i7SJqUWHb5nd202BlGUsDMzQUaNIqJxZHDM1UoaaU4AYca/4/7uHA6+9/xietdGp9OMfAsGSaWw/anH8twIpUexF49tnlLLB12ZRHE+feX+YEoBrBwucXHmLB3RwRI3frUqr5L5WuZncRT41IXIuXJtoLs8iwFFvxIbCvoOEZEJcuVItk9/2WCjtJFy0hukVxXruwq2UWrfnp6g2YFWnTuIJ3s8poJyTpZFQ+pXj4gDNQ4/aM9iktk47xSj+uJYmjNi7aago4KL4uz7ToVa+C6bAwJS+KnPYEzZ+RsvJxvhj+HdHEDPmMD4wITAJBgUrDgMCGgUABBQpoyWh2x8CegH7d1oBQ6I6gmV8RQQUaOSZMKU+XupnJgIm3Wj2ulpaQscCAwGGoA=="
          alias: "Test"
          keyStorePassword: "Test@8866"
          keyPassword: "Test@8866"
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs
